stages:
  - lint


jobs:
  include:
    - stage: lint
      language: python
      python:
        - "3.7"
        - "3.7-dev"
      install:
        - pip install flake8
      script:
        - flake8 .
